#!/usr/bin/env python

"""
SCons build file for ExecuTorch Godot module
"""

Import("env")

module_env = env.Clone()

module_env.Append(CPPPATH=["."])

if env["platform"] == "linuxbsd":
    module_env.Append(CPPFLAGS=["-std=c++17"])
elif env["platform"] == "windows":
    module_env.Append(CPPFLAGS=["/std:c++17"])
elif env["platform"] == "osx":
    module_env.Append(CPPFLAGS=["-std=c++17"])

module_env.add_source_files(env.modules_sources, "*.cpp")
